# Generated by Django 5.1 on 2024-10-06 14:55

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                (
                    'image',
                    cloudinary.models.CloudinaryField(
                        default='default_post_uu0i5n',
                        max_length=255,
                        verbose_name='post_image'
                    )
                ),
                (
                    'image_filter',
                    models.CharField(
                        choices=[
                            ('_1977', '1977'),
                            ('brannan', 'Brannan'),
                            ('earlybird', 'Earlybird'),
                            ('hudson', 'Hudson'),
                            ('inkwell', 'Inkwell'),
                            ('lofi', 'Lo-Fi'),
                            ('kelvin', 'Kelvin'),
                            ('normal', 'Normal'),
                            ('nashville', 'Nashville'),
                            ('rise', 'Rise'),
                            ('toaster', 'Toaster'),
                            ('valencia', 'Valencia'),
                            ('walden', 'Walden'),
                            ('xpro2', 'X-pro II')
                        ],
                        default='normal',
                        max_length=32
                    )
                ),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL
                    )
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
