# Generated by Django 5.1 on 2024-10-06 15:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_post_uu0i5n', max_length=255, verbose_name='post_image'),
        ),
    ]
