# Generated by Django 5.1 on 2024-10-06 15:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default='default_post_uu0i5n',
                max_length=255,
                null=True,
                verbose_name='post_image'
            ),
        ),
    ]
