# Generated by Django 5.1 on 2024-10-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_private',
        ),
    ]
