# Generated by Django 5.1 on 2024-10-06 01:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default_profile_wxoxmn', max_length=255, verbose_name='profile_picture'),
        ),
    ]
